package es.mercadona.gesaduan.business.declaracionesdevalorapi.putfacturaconfirmadescarga.v1;

import es.mercadona.gesaduan.dto.declaracionesdevalorapi.putfacturaconfirmadescarga.v1.InputPutFacturaConfirmaDescargaDTO;
import es.mercadona.gesaduan.dto.declaracionesdevalorapi.putfacturaconfirmadescarga.v1.restfull.OutputPutFacturaConfirmaDescargaDTO;

public interface PutFacturaConfirmaDescargaService {
	public OutputPutFacturaConfirmaDescargaDTO updateEstadoDescarga(InputPutFacturaConfirmaDescargaDTO input);
}