package es.mercadona.gesaduan.business.equipotransporte.getequipotransportedetalle.v1;

import es.mercadona.gesaduan.dto.equipotransporte.getequipotransportedetalle.v1.InputEquipoTransporteDetalleDTO;
import es.mercadona.gesaduan.dto.equipotransporte.getequipotransportedetalle.v1.restfull.OutputEquipoTransporteDetalleDTO;

public interface GetEquipoTransporteDetalleService {	
	public OutputEquipoTransporteDetalleDTO getEquipoTransporteDetalle(InputEquipoTransporteDetalleDTO input);	
}
